In [1]:
%matplotlib inline
import data_util
import matplotlib.pyplot as plt
import numpy as np
from data_util import DataPoint
import math
from LDPC.LDPCGenerator import LDPCCoder

In [2]:
def num_to_bin(x, length=None):
    '''
    convert a single lable to corresponding binary vector
    '''
    if length == None:
        length=int(math.log(x)/math.log(2)) + 1
    bits = [0]*length
    i = 0
    while x:
        bits[i] = x%2
        x >>= 1
        i+=1
    return bits

def l_to_vec(labels, k, length):
    '''
    compress the lable vector.
    input:
        k: maximum non-zero entries of lable in a data point
        length: length of each binary bevtor for a label
    '''

    labels.sort() #ascending order
    default_place = [1]*length
    vec = []
    for i in range(k):
        if i < len(labels):
            vec.extend(num_to_bin(labels[i], length))
        else:
            vec.extend(default_place)
    return (np.array(vec))
    
l_to_vec([1,2,3], 4, 2)


array([1, 0, 0, 1, 1, 1, 1, 1])

In [3]:
n = 10 # we can translate 10 bits.
ldpc = LDPCCoder(n)

# message_to_send is an integer from 0 to 1<<n-1.
message_to_send = num_to_bin(1000)
# Select the message_to_send-th column.
received_codeword = ldpc.encode(1000)



decode_mss = ldpc.decode(received_codeword)



#if decode_result == message_to_send:
#    print 'Decoding correct'
#else:
#    print 'Decoding error'

In [5]:
decode_mss

NameError: name 'decode_mss' is not defined

In [6]:
ldpc.code_length

24

In [7]:
ldpc.message_length

14

In [8]:
num_to_bin(100)

[0, 0, 1, 0, 0, 1, 1]

In [13]:
mss = ldpc.encode([0, 0, 0, 1, 0, 1, 1, 1, 1, 1])

In [14]:
mss

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0])

In [15]:
for i in xrange(len(mss)):
    if np.random.rand() > 0.95:
        mss[i] = 1 - mss[i]

In [16]:
ldpc.decode(mss)

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 1])

In [44]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.externals import joblib

In [63]:
X_tr = np.random.rand(15000, 5000)
Y_tr = np.random.binomial(1, 0.5, 15000)
Y_tr

array([0, 0, 1, ..., 0, 1, 0])

In [66]:
clf = LogisticRegression(solver='sag')
clf.fit(X=X_tr, y=Y_tr)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='sag', tol=0.0001,
          verbose=0, warm_start=False)

In [65]:
clf.predict(np.random.rand(1,5000))

array([0])

In [56]:
joblib.dump(clf, ".model")

['.model']

In [49]:
clf2 = joblib.load(".model")

In [60]:
clf2.predict(np.random.rand(1,5000))

array([1])